version: "3"
services:
  react-app:
    build:
      context: .
      args:
        REACT_APP_API_BASE_URL: http://localhost:8080
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
